#!/usr/bin/env python3
import json
import subprocess
import sys
import os

# Colors for pretty printing
class Colors:
    HEADER = '\033[95m'
    BLUE = '\033[94m'
    GREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'

def print_header(text):
    print(f"\n{Colors.HEADER}{Colors.BOLD}=== {text} ==={Colors.ENDC}")

def print_step(number, title, description):
    print(f"\n{Colors.BLUE}{Colors.BOLD}Step {number}: {title}{Colors.ENDC}")
    print(f"{description}")

def print_command(command):
    print(f"\n{Colors.GREEN}$ {command}{Colors.ENDC}")

def get_terraform_outputs():
    # Priority 1: Check for outputs.json (generated by manual deploy.sh)
    if os.path.exists("outputs.json"):
        print("Reading outputs.json...")
        with open("outputs.json", "r") as f:
            return json.load(f)

    # If missing, instruct user to run deploy script
    print(f"{Colors.FAIL}Error: 'outputs.json' not found.{Colors.ENDC}")
    print("Please run the deployment script first to generate this file:")
    print(f"{Colors.GREEN}./deploy.sh{Colors.ENDC}")
    sys.exit(1)

def main():
    print(f"{Colors.BOLD}AWS S3 Advanced Demo - Presenter Guide{Colors.ENDC}")
    print("------------------------------------------")

    outputs = get_terraform_outputs()
    
    # Extract values safely
    website_url = outputs.get('website_endpoint', {}).get('value', 'N/A')
    presign_cmd = outputs.get('s3_presign_command', {}).get('value', 'N/A')
    direct_url = outputs.get('secret_file_direct_url', {}).get('value', 'N/A')
    auditor_cmd = outputs.get('auditor_access_command', {}).get('value', 'N/A')
    auditor_arn = outputs.get('auditor_access_point_arn', {}).get('value', 'N/A')
    
    # Step 1: Website
    print_step(1, "Static Website Hosting", "Show the public website running securely on S3.")
    print(f"Open this URL in your browser:\n{Colors.UNDERLINE}{website_url}{Colors.ENDC}")
    input(f"\nPress {Colors.BOLD}Enter{Colors.ENDC} to continue to the next step...")

    # Step 2: Pre-signed URL
    print_step(2, "Pre-signed URL (Security Demo)", "Demonstrate that private files are inaccessible, then generate a temporary link.")
    print("1. Try to open this Direct Link (Should fail/403):")
    print(f"   {Colors.FAIL}{direct_url}{Colors.ENDC}")
    
    print("\n2. Generate a Pre-signed URL by running this command:")
    print_command(presign_cmd)
    print("   (Copy and paste the output URL into your browser)")
    input(f"\nPress {Colors.BOLD}Enter{Colors.ENDC} to continue...")

    # Step 3: Access Points
    print_step(3, "S3 Access Points (Auditor)", "Show how specific endpoints can have restricted views.")
    print("1. List logs using the Auditor Access Point (Should succeed):")
    print_command(auditor_cmd)
    
    # Add simulation tip
    print(f"\n   {Colors.WARNING}Note:{Colors.ENDC} If the log list is empty (logs take time to deliver), run this to simulate data:")
    print(f"   {Colors.GREEN}echo 'Simulated Log' > dummy.txt && aws s3 cp dummy.txt s3://{outputs['log_bucket_name']['value']}/log/sim-log.txt{Colors.ENDC}")
    
    print("\n2. Try to steal the secret using the Auditor Access Point (Should Access Denied):")
    # Construct the steal command
    steal_cmd = f"aws s3 cp s3://{auditor_arn}/secret.txt -"
    print_command(steal_cmd)

    print(f"\n   {Colors.WARNING}Note:{Colors.ENDC} If this SUCCEEDS (because you are Admin), run this script to enforce strict security:")
    print(f"   {Colors.GREEN}./fix_policy.sh{Colors.ENDC}")
    print("   Then try the steal command again - it will be DENIED.")

    print("\n3. Verify that the Pre-signed URL from Step 2 STILL works:")
    print("   (Access Point policies do not affect direct bucket access/pre-signed URLs)")
    print(f"   {Colors.GREEN}Go back to your browser and refresh the pre-signed link.{Colors.ENDC}")
    
    print_header("Demo Complete")
    print("To clean up, you must manually delete the buckets and access point:")
    print(f"1. aws s3 rb s3://{outputs['website_endpoint']['value'].split('http://')[1].split('.s3')[0]} --force")
    print(f"2. aws s3 rb s3://{outputs['log_bucket_name']['value']} --force")
    print(f"3. aws s3control delete-access-point --name {auditor_arn.split('/')[-1]} --account-id {auditor_arn.split(':')[4]}")

if __name__ == "__main__":
    main()
